# Generated by Django 5.1.6 on 2025-03-06 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_url', models.URLField()),
                ('search', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='home.usersearchhistory')),
            ],
        ),
    ]
