# Generated by Django 5.1.6 on 2025-03-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_studentprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='quiz_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
